version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ..:/var/www/html:z
      - composer:/tmp
    user: $USER
    links:
      - database

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
        - "8000:8000"
    volumes:
        - ..:/var/www/html:z
        - ./nginx.conf:/etc/nginx/conf.d/default.conf:z
    links:
        - php

  database:
    image: mariadb:10.7
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=fusionsuite
      - MARIADB_USER=fusionsuite
      - MARIADB_PASSWORD=fusionsuite
      - MARIADB_DATABASE=fusionsuite_development

volumes:
    composer: {}

networks:
  default:
    name: fusionsuite-network
